sonarqube:
  image: nci_fastest/sonarqube
  ports:
    - "9000:9000"
    - "9092:9092"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db_1:5432/sonar

db:
  image: postgres
  volumes_from:
    - datadb
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

datadb:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: /bin/true


