hub:
  image: nci_fastest/grid
  ports:
    - "4444:4444"
firefox:
  image: nci_fastest/node
  expose:
    - "5555"
jenkins:
  image: nci_fastest/jenkins
  ports:
  - "8080:8080"
  volumes:
    - /home/nci/.jenkins/:/var/jenkins_home
    - /home/nci/.m2/repository:/root/.m2/repository
